### ISSUE TITLE
Should this CSS task belong here?

### ISSUE THREAD

**Issue by zenorocha** [metal/gulp-metal#16]
https://github.com/metal/gulp-metal/blob/master/lib/tasks/css.js

Gulp Metal assumes that an user wants to build CSS files with SASS and concatenate them. I think that's too opinionated for a JS-only project.

**Comment by mairatma** [comment]
The idea of gulp-metal is to be a tool that can help with the most common use cases of creating metal components. We almost always just want to allow individual metal components to use scss and provide a final css file to developers using them. Bigger projects like sites using metal will need their own css task, since that will definitely require more thought depending on the use case. We just wanted to provide a simple option so simple projects don't need to have it copy/pasted every time.
